version: '3.9'
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: contacts
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql script

  web:
    build: ./
    container_name: web
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html

volumes:
  db_data: